### ISSUE TITLE
Bug: Unable to configure Keycloak SSO

### ISSUE THREAD

**Issue by praveen-livspace** [OneUptime/oneuptime#1406]
**Describe the bug**
Signature validation fails on authenticating with Keycloak. 
```

2024-05-14 17:01:30.750 | Error: error:1E08010C:DECODER routines::unsupported |  
-- | -- | --
  |   | 2024-05-14 17:01:30.750 | at Verify.verify (node:internal/crypto/sig:224:24) |  
  |   | 2024-05-14 17:01:30.750 | at RSASHA256.verifySignature (/usr/src/app/node_modules/xml-crypto/lib/signed-xml.js:116:24) |  
  |   | 2024-05-14 17:01:30.750 | at SignedXml.validateSignatureValue (/usr/src/app/node_modules/xml-crypto/lib/signed-xml.js:442:20) |  
  |   | 2024-05-14 17:01:30.750 | at SignedXml.checkSignature (/usr/src/app/node_modules/xml-crypto/lib/signed-xml.js:376:15) |  
  |   | 2024-05-14 17:01:30.750 | at Function.isSignatureValid (/usr/src/app/FeatureSet/Identity/Utils/SSO.ts:138:38) |  
  |   | 2024-05-14 17:01:30.750 | at loginUserWithSso (/usr/src/app/FeatureSet/Identity/API/SSO.ts:247:26) |  
  |   | 2024-05-14 17:01:30.750 | at processTicksAndRejections (node:internal/process/task_queues:95:5) |  
  |   | 2024-05-14 17:01:30.750 | at async /usr/src/app/FeatureSet/Identity/API/SSO.ts:134:16 { |  
  |   | 2024-05-14 17:01:30.750 | library: 'DECODER routines', |  
  |   | 2024-05-14 17:01:30.750 | reason: 'unsupported', |  
  |   | 2024-05-14 17:01:30.750 | code: 'ERR_OSSL_UNSUPPORTED' |  
  |   | 2024-05-14 17:01:30.750 | } |  
  |   | 2024-05-14 17:01:30.751 | BadRequestException [Error]: Signature is not valid or Public Certificate configured with this SSO provider is not valid |  
  |   | 2024-05-14 17:01:30.751 | at loginUserWithSso (/usr/src/app/FeatureSet/Identity/API/SSO.ts:255:21) |  
  |   | 2024-05-14 17:01:30.751 | at processTicksAndRejections (node:internal/process/task_queues:95:5) |  
  |   | 2024-05-14 17:01:30.751 | at async /usr/src/app/FeatureSet/Identity/API/SSO.ts:134:16 { |  
  |   | 2024-05-14 17:01:30.751 | _code: 400 |  
  |   | 2024-05-14 17:01:30.751 | }



```
**To Reproduce**
1. Configure SAML SSO for any project using keycloak.
2. Configure the details.
3. Try logging in using the test link

**Expected behavior**
User should be able to login.

**Screenshots**

**Deployment Type**
Self Hosted: 7.0.2270

**Additional context**

**Comment by simlarsen** [comment]
Are you sure you're using correct signature methods?
