### ISSUE TITLE
Error connecting to server when verifying CNAME

### ISSUE THREAD

**Issue by benjaminscheuerer** [OneUptime/oneuptime#1692]
**Describe the bug**
CNAME Record on self-hosted OneUptime cannot be verified. Connection to server not possible.

**To Reproduce**

Go to Project Setting add Custom Domain and TXT Record on DNS Server to verify the domain
Go to Status Page >> Custom Domain  --> create status page domain and verify CNAME

**Expected behavior**
CNAME should be verified.

**Screenshots**
![image](https://github.com/user-attachments/assets/a2fe1e2d-6da5-4c07-a367-1e0e805cb9df)
![image](https://github.com/user-attachments/assets/0987ab76-af3a-496b-a3d2-be5f00f8824a)

**Deployment Type**
self hosted (7.0.3018)

**Additional context**
DNS settings seem to be correct. Resolution within the docker container is possible.
Which server is ment in the error message?

**Comment by benjaminscheuerer** [comment]
In the Container logs I get the following error:

BadDataException [Error]: Cname is not valid for domain status1.teccle.cloud
    at fn (/usr/src/Common/Server/Utils/Greenlock/Greenlock.ts:215:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.orderCert (/usr/src/Common/Server/Utils/Greenlock/Greenlock.ts:171:12)
    at async fn (/usr/src/Common/Server/Services/StatusPageDomainService.ts:132:11)
    at async fn (/usr/src/Common/Server/Services/StatusPageDomainService.ts:437:15)
    at async fn (/usr/src/app/FeatureSet/Workers/Jobs/StatusPageCerts/StatusPageCerts.ts:55:11)
    at async /usr/src/app/FeatureSet/Workers/Jobs/StatusPageCerts/StatusPageCerts.ts:42:12
    at async Function.runJobWithTimeout (/usr/src/Common/Server/Infrastructure/QueueWorker.ts:49:12)
    at async Worker.QueueWorker_1.default.getWorker.concurrency [as processFn] (/usr/src/app/FeatureSet/Workers/Index.ts:107:13)
    at async Worker.processJob (/usr/src/Common/node_modules/bullmq/src/classes/worker.ts:792:22)
    at async Worker.retryIfFailed (/usr/src/Common/node_modules/bullmq/src/classes/worker.ts:998:16) {
  _code: 400
}
