### ISSUE TITLE
Probes disconnected with 'Failed to register probe'

### ISSUE THREAD

**Issue by wendellli99** [OneUptime/oneuptime#1760]
**Describe the bug**
Probes disconnected suddenly, likely after an update. I have tried `npm update`, `npm stop` and `npm start`.

```
Failed to register probe. Retrying after 30 seconds...
APIException [Error]: Error occurred while making request to http://ingestor:3400/probe-ingest/register.
    at Function.getErrorResponse (/usr/src/Common/Utils/API.ts:461:11)
    at Function.fetch (/usr/src/Common/Utils/API.ts:439:30)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Function.post (/usr/src/Common/Utils/API.ts:329:12)
    at async Function._registerProbe (/usr/src/app/Services/Register.ts:125:48)
    at async Function.registerProbe (/usr/src/app/Services/Register.ts:102:9)
    at async runFunction (/usr/src/app/Jobs/Alive.ts:29:7)
    at async Task._execution (/usr/src/Common/Server/Utils/BasicCron.ts:24:7) {
  _code: 2,
  _error: AxiosError: getaddrinfo EAI_AGAIN ingestor
      at Function.AxiosError.from (/usr/src/Common/node_modules/axios/lib/core/AxiosError.js:92:14)
      at RedirectableRequest.handleRequestError (/usr/src/Common/node_modules/axios/lib/adapters/http.js:620:25)
      at RedirectableRequest.emit (node:events:519:28)
      at RedirectableRequest.emit (node:domain:488:12)
      at ClientRequest.eventHandlers.<computed> (/usr/src/Common/node_modules/follow-redirects/index.js:49:24)
      at ClientRequest.emit (node:events:519:28)
      at ClientRequest.emit (node:domain:488:12)
      at emitErrorEvent (node:_http_client:103:11)
      at Socket.socketErrorListener (node:_http_client:506:5)
      at Socket.emit (node:events:519:28)
      at Socket.emit (node:domain:488:12)
      at emitErrorNT (node:internal/streams/destroy:170:8)
      at emitErrorCloseNT (node:internal/streams/destroy:129:3)
      at processTicksAndRejections (node:internal/process/task_queues:90:21)
      at Axios.request (/usr/src/Common/node_modules/axios/lib/core/Axios.js:45:41)
      at processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async Function.fetch (/usr/src/Common/Utils/API.ts:403:20)
      at async Function.post (/usr/src/Common/Utils/API.ts:329:12)
      at async Function._registerProbe (/usr/src/app/Services/Register.ts:125:48)
      at async Function.registerProbe (/usr/src/app/Services/Register.ts:102:9)
      at async runFunction (/usr/src/app/Jobs/Alive.ts:29:7)
      at async Task._execution (/usr/src/Common/Server/Utils/BasicCron.ts:24:7) {
    hostname: 'ingestor',
    syscall: 'getaddrinfo',
    code: 'EAI_AGAIN',
    errno: -3001,
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      method: 'post',
      url: 'http://ingestor:3400/probe-ingest/register',
      data: '{"probeKey":"8A3Nuvh4JNmA37u2o4xsRHRtBhuHgfAn","probeName":"Probe-1","probeDescription":"Global","clusterKey":"yJ%2BEd3Zr7wPbHueCWqBsSrldKCUVOMqCtJmjzQaO19s%3D"}'
    },
    request: Writable {
      _events: [Object],
      _writableState: [WritableState],
      _maxListeners: undefined,
      _options: [Object],
      _ended: false,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 161,
      _requestBodyBuffers: [Array],
      _eventsCount: 3,
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [ClientRequest],
      _currentUrl: 'http://ingestor:3400/probe-ingest/register',
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false
    },
    cause: Error: getaddrinfo EAI_AGAIN ingestor
        at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
      errno: -3001,
      code: 'EAI_AGAIN',
      syscall: 'getaddrinfo',
      hostname: 'ingestor'
    }
  }
}
```

**Expected behavior**
Probes should be working.

**Screenshots**
<img width="237" alt="Screenshot 2024-12-05 at 13 33 04" src="https://github.com/user-attachments/assets/04cfff1a-10f0-4bbc-bfa0-581117f5a821">

**Deployment Type**
Self-host with docker-compose. Version 7.0.3343.

**Comment by simlarsen** [comment]
Is this docker compose? In this case change `GLOBAL_PROBE_1_ONEUPTIME_URL` to `http://localhost`

**Comment by wendellli99** [comment]
Looks like my `config.env` file is out of date. I copied the new `config.env` file and only changed the below values, all other values else are kept the same.

```
# Please change this to domain of the server where oneuptime is hosted on.
HOST=oneuptime.mydomain.com

# OneUptime Port. This is the port where OneUptime will be hosted on. 
ONEUPTIME_HTTP_PORT=80

# ==============================================
# SETTING UP TLS/SSL CERTIFICATES
# ==============================================
# OneUptime DOES NOT support setting up SSL/TLS certificates. You need to setup SSL/TLS certificates on your own.
# If you need to use SSL/TLS certificates, then you need to use a reverse proxy like Nginx/Caddy and use LetsEncrypt to provision the certificates.
# You then need to point the reverse proxy to the OneUptime server.
# Once you have done that, 
# - You can set the HTTP_PROTOCOL to https
# - Change the HOST to the domain name of the server where reverse proxy is hosted.
HTTP_PROTOCOL=http

# Secrets - PLEASE CHANGE THESE. Please change these to something random. All of these can be different values.
ONEUPTIME_SECRET=***************
DATABASE_PASSWORD=***************
CLICKHOUSE_PASSWORD=***************
REDIS_PASSWORD=***************
ENCRYPTION_SECRET=***************
GLOBAL_PROBE_1_KEY=***************
GLOBAL_PROBE_2_KEY=***************
INTERNAL_SMTP_PASSWORD=***************

# If you are connecting Status Pages to custom domains, then this will be the port where the status page will be hosted on.
# This should be https port because oneuptime automatically generates ssl certs from lets encrypt. 
STATUS_PAGE_HTTPS_PORT=443

# If you would like to attach status page to custom domains use this setting.
# For example, lets say you would like the status page to be hosted on status.yourcompany.com, then 
# 1. Create a A record in your DNS provider with the name "oneuptime.yourcompany.com" and value to Public IP of the server oneuptime is deployed on.
# 2. Set the STATUS_PAGE_CNAME_RECORD to "oneuptime.yourcompany.com"
# 3. Create CNAME record in your DNS provider with the name "status.yourcompany.com" and value "oneuptime.yourcompany.com"
STATUS_PAGE_CNAME_RECORD=oneuptime.mydomain.com
```
After `npm stop`, `npm start`, and `npm run update`, I'm seeing the below error when visiting the home page.
<img width="538" alt="Screenshot 2024-12-06 at 16 23 50" src="https://github.com/user-attachments/assets/cf7b3830-73ac-4619-893a-1554888d0fdf">
