### ISSUE TITLE
<Title of the issue>

### ISSUE THREAD

**Issue by DrDrrae** [OneUptime/oneuptime#1771]
**Describe the bug**
Monitor metrics page doesn't load. The page starts to load then just results in a blank window.
In the browser console, two React errors are shown:

```
Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. react-dom.production.min.js:188 Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full react-dom.production.min.js:188
    at Uh (react-dom.production.min.js:161:296)
    at Wh (react-dom.production.min.js:163:16)
    at Object.useState (react-dom.production.min.js:179:521)
    at exports.useState (react.production.min.js:26:217)
    at MonitorMetricsElement (MonitorMetrics.tsx:283:55)
    at Nh (react-dom.production.min.js:160:135)
    at cj (react-dom.production.min.js:196:256)
    at Vk (react-dom.production.min.js:291:18)
    at Uk (react-dom.production.min.js:279:383)
    at Tk (react-dom.production.min.js:279:319)

Uncaught Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. react-dom.production.min.js:161
    at Uh (react-dom.production.min.js:161:296)
    at Wh (react-dom.production.min.js:163:16)
    at Object.useState (react-dom.production.min.js:179:521)
    at exports.useState (react.production.min.js:26:217)
    at MonitorMetricsElement (MonitorMetrics.tsx:283:55)
    at Nh (react-dom.production.min.js:160:135)
    at cj (react-dom.production.min.js:196:256)
    at Vk (react-dom.production.min.js:291:18)
    at Uk (react-dom.production.min.js:279:383)
    at Tk (react-dom.production.min.js:279:319)
```

**To Reproduce**
1. Go to monitors
2. Click on any monitor
3. Click on metrics

**Expected behavior**
Metrics page should load

**Screenshots**
![image](https://github.com/user-attachments/assets/100a93d4-8cf3-4fb9-9a79-ac6108efd0ea)
![image](https://github.com/user-attachments/assets/4253bcad-18fd-4d1b-a351-dc8089abe136)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge, Chrome, and Firefox
 - Version 131.0.2903.99, 131.0.6778.140, 133.0.3 

**Deployment Type**
Self-hosted, recently updated to 7.0.3387, then to 7.0.3393. Unsure what previous version was.

**Additional context**
This used to work until the upgrade.

**Comment by simlarsen** [comment]
This is fixed!
