### ISSUE TITLE
DB connection error

### ISSUE THREAD

**Issue by Geekster-Alan** [OneUptime/oneuptime#355]
**Describe the bug**
Following the instructions to setup on a clean VM, all containers start not the postgres container shows the below error;

`psql: error: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  role "root" does not exist`

**To Reproduce**
Run the `bash install.sh` script after completing the needed details in the config.env

**Expected behavior**
Database to connect to allow the system to be used. 

**Desktop (please complete the following information):**
 - OS: Ubuntu22.04

![ubuntu2004_BiG1HnNUvA](https://user-images.githubusercontent.com/8240568/215984295-7ed5da5b-6fb4-4bb4-97cb-d34489cc53a4.png)

**Comment by coln1** [comment]
i had the same problem on ubuntu 20.04 
i changed the install.sh to this 
`#!/usr/bin/env bash

set -e
set -a
source $PWD/config.env
set +`

however the dashboard is failing with auth failure 
`  message: 'password authentication failed for user "oneuptimedbuser"`

looking at the config.env there is no user with that account and there isnt one created in DB

`postgres-# \du
                                   List of roles
 Role name |                         Attributes                         | Member of
-----------+------------------------------------------------------------+-----------
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}`

**Comment by coln1** [comment]
to export the env i had to comment out <planMonthlyId>,<planYearlyId> dunno if that would have caused the auth failure

**Comment by Chillrend** [comment]
I also experiencing the same as @Geekster-Alan, the exact error is happening in `install.sh` but the app, and the postgres container does start. When i tried submitting the register form, the following error logs appear in the `oneuptime-worker` container.

```
{
  message: 'Unhandled rejection in server process occurred',
  level: 'error',
  timestamp: '2023-02-09T01:23:00.888Z'
}
{
  _code: 3,
  level: 'error',
  message: 'Database not connected',
  stack: 'Error: Database not connected\n' +
    '    at Service.getRepository (/usr/src/CommonServer/Services/DatabaseService.ts:96:19)\n' +
    '    at Service._findBy (/usr/src/CommonServer/Services/DatabaseService.ts:815:57)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Service.findBy (/usr/src/CommonServer/Services/DatabaseService.ts:758:16)\n' +
    '    at async /usr/src/app/Jobs/ScheduledMaintenance/SendEmailToSubscribers.ts:26:9\n' +
    '    at async Task._execution (/usr/src/app/Utils/Cron.ts:12:13)',
  timestamp: '2023-02-09T01:23:00.888Z'
}
{
  message: Promise {
    <rejected> DatabaseNotConnectedException [Error]: Database not connected
        at Service.getRepository (/usr/src/CommonServer/Services/DatabaseService.ts:96:19)
        at Service._findBy (/usr/src/CommonServer/Services/DatabaseService.ts:815:57)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Service.findBy (/usr/src/CommonServer/Services/DatabaseService.ts:758:16)
        at async /usr/src/app/Jobs/ScheduledMaintenance/SendEmailToSubscribers.ts:26:9
        at async Task._execution (/usr/src/app/Utils/Cron.ts:12:13) {
      _code: 3,
      level: 'error',
      [Symbol(level)]: 'error'
    }
  },
  level: 'error',
  timestamp: '2023-02-09T01:23:00.888Z'
  ```

**Comment by Chillrend** [comment]
Apparently, modifying `install.sh` with @coln1 snippets fixes the database problem

```bash
#!/usr/bin/env bash

set -e
set -a
source $PWD/config.env
set +
```
No more `psql: error: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  role "root" does not exist
Database created` errors when running `install.sh`

```
Already up to date.
[+] Running 15/15
 ⠿ alert Pulled                                                                                                                                                                                                         2.7s
 ⠿ workflow Pulled                                                                                                                                                                                                      2.6s
 ⠿ dashboard-api Pulled                                                                                                                                                                                                 2.6s
 ⠿ workers Pulled                                                                                                                                                                                                       2.6s
 ⠿ haraka Pulled                                                                                                                                                                                                        2.6s
 ⠿ home Pulled                                                                                                                                                                                                          2.5s
 ⠿ file Pulled                                                                                                                                                                                                          2.6s
 ⠿ status-page Pulled                                                                                                                                                                                                   2.6s
 ⠿ dashboard Pulled                                                                                                                                                                                                     2.7s
 ⠿ redis Pulled                                                                                                                                                                                                         2.7s
 ⠿ accounts Pulled                                                                                                                                                                                                      2.6s
 ⠿ postgres Pulled                                                                                                                                                                                                      2.7s
 ⠿ mail Pulled                                                                                                                                                                                                          2.5s
 ⠿ nginx Pulled                                                                                                                                                                                                         2.6s
 ⠿ identity Pulled                                                                                                                                                                                                      2.7s
[+] Running 2/2
 ⠿ Network oneuptime_default       Created                                                                                                                                                                              0.1s
 ⠿ Container oneuptime-postgres-1  Started                                                                                                                                                                              0.9s
CREATE DATABASE

> app@3.0.2 start
> sudo docker compose up -d $npm_config_services

[+] Running 15/15
 ⠿ Container oneuptime-redis-1          Started                                                                                                                                                                         1.9s
 ⠿ Container oneuptime-home-1           Started                                                                                                                                                                         2.0s
 ⠿ Container oneuptime-haraka-1         Started                                                                                                                                                                         2.0s
 ⠿ Container oneuptime-postgres-1       Running                                                                                                                                                                         0.0s
 ⠿ Container oneuptime-file-1           Started                                                                                                                                                                         1.9s
 ⠿ Container oneuptime-mail-1           Started                                                                                                                                                                         2.7s
 ⠿ Container oneuptime-workflow-1       Started                                                                                                                                                                         4.1s
 ⠿ Container oneuptime-dashboard-api-1  Started                                                                                                                                                                         4.3s
 ⠿ Container oneuptime-identity-1       Started                                                                                                                                                                         4.3s
 ⠿ Container oneuptime-alert-1          Started                                                                                                                                                                         3.8s
 ⠿ Container oneuptime-workers-1        Started                                                                                                                                                                         4.2s
 ⠿ Container oneuptime-accounts-1       Started                                                                                                                                                                         5.4s
 ⠿ Container oneuptime-dashboard-1      Started                                                                                                                                                                         6.8s
 ⠿ Container oneuptime-status-page-1    Started                                                                                                                                                                         6.9s
 ⠿ Container oneuptime-nginx-1          Started                                                                                                                                                                         8.1s
We will need to wait ~5-10 minutes for things to settle down, migrations to finish, and TLS certs to be issued
```

**Comment by skeels78** [comment]
> Apparently, modifying `install.sh` with @coln1 snippets fixes the database problem
> 
> ```shell
> #!/usr/bin/env bash
> 
> set -e
> set -a
> source $PWD/config.env
> set +
> ```

Has anyone else _NOT_ had this resolve this issue?
I ran the installer with the for-mentioned modifications (which did solve the "no root user issue during the install") but I still receive the following error from the **identity** container when trying to create a new account from the web gui:
```
{
  message: Promise {
    <rejected> DatabaseNotConnectedException [Error]: Database not connected
        at Service.getRepository (/usr/src/CommonServer/Services/DatabaseService.ts:96:19)
        at Service._findBy (/usr/src/CommonServer/Services/DatabaseService.ts:815:57)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Service.findOneBy (/usr/src/CommonServer/Services/DatabaseService.ts:920:46)
        at async /usr/src/app/API/AuthenticationAPI.ts:66:51 {
      _code: 3
    }
  },
  level: 'error',
  timestamp: '2023-02-14T20:40:39.422Z'
}
```
What other info can I provide to troubleshoot this?

**Comment by simlarsen** [comment]
This should be fixed. Please re-open if this is not the case.
