### ISSUE TITLE
I keep getting this error when trying to install the project 

### ISSUE THREAD

**Issue by iamsethsamuel** [OneUptime/oneuptime#366]
**Describe the bug**
I ran the bash preinstall.sh command and I keep getting the error below
node:internal/modules/cjs/loader:1039
  const err = new Error(message);
              ^

Error: Cannot find module 'typescript'
Require stack:
- /usr/local/lib/node_modules/ts-node/dist/util.js
- /usr/local/lib/node_modules/ts-node/dist/index.js
- /usr/local/lib/node_modules/ts-node/dist/esm.js
- /usr/local/lib/node_modules/ts-node/dist/child/child-loader.js
- /usr/local/lib/node_modules/ts-node/child-loader.mjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at projectLocalResolveHelper (/usr/local/lib/node_modules/ts-node/dist/util.js:117:24)
    at resolveCompiler (/usr/local/lib/node_modules/ts-node/dist/configuration.js:232:22)
    at resolveAndLoadCompiler (/usr/local/lib/node_modules/ts-node/dist/configuration.js:225:26)
    at findAndReadConfig (/usr/local/lib/node_modules/ts-node/dist/configuration.js:48:28)
    at phase3 (/usr/local/lib/node_modules/ts-node/dist/bin.js:254:67)
    at bootstrap (/usr/local/lib/node_modules/ts-node/dist/bin.js:47:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/ts-node/dist/child/child-entrypoint.js:23:21)
    at Module._compile (node:internal/modules/cjs/loader:1218:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/ts-node/dist/util.js',
    '/usr/local/lib/node_modules/ts-node/dist/index.js',
    '/usr/local/lib/node_modules/ts-node/dist/esm.js',
    '/usr/local/lib/node_modules/ts-node/dist/child/child-loader.js',
    '/usr/local/lib/node_modules/ts-node/child-loader.mjs'
  ]
}
**To Reproduce**

**Expected behavior**
The script to install and the packages to run

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntun]
recent:///1c2ee3c73b1a55f7bd8b120d63ed0798
**Smartphone (please complete the following information):**

**Additional context**

**Comment by simlarsen** [comment]
This should be fixed. Please let me know if this is not the case
