### ISSUE TITLE
Can not open profile

### ISSUE THREAD

**Issue by tankerkiller125** [OneUptime/oneuptime#461]
Describe the bug
Not possible to open the profile page

(Maybe it's related to #460 somehow?)

To Reproduce

Use self-hosted version
Go to 'Profile'
Page is empty

Expected behavior
Possibility to view and edit profile

Get the following console log:
```
(index):64  cdn.tailwindcss.com should not be used in production. To use Tailwind CSS in production, install it as a PostCSS plugin or use the Tailwind CLI: https://tailwindcss.com/docs/installation
(anonymous) @ (index):64
ma:1  Manifest: Line: 1, column: 1, Syntax error.
react-dom.production.min.js:189  Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B_title%2C%20_name%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at th (react-dom.production.min.js:152:54)
    at J (react-dom.production.min.js:162:372)
    at Yi (react-dom.production.min.js:192:291)
    at Wk (react-dom.production.min.js:294:1)
    at Vk (react-dom.production.min.js:280:383)
    at Uk (react-dom.production.min.js:280:319)
    at Jk (react-dom.production.min.js:280:180)
    at Ok (react-dom.production.min.js:271:86)
    at Hk (react-dom.production.min.js:268:399)
    at J (scheduler.production.min.js:13:197)
Mi @ react-dom.production.min.js:189
Oi.c.callback @ react-dom.production.min.js:189
ih @ react-dom.production.min.js:144
lk @ react-dom.production.min.js:262
jk @ react-dom.production.min.js:260
ik @ react-dom.production.min.js:259
Xk @ react-dom.production.min.js:283
Qk @ react-dom.production.min.js:281
Hk @ react-dom.production.min.js:269
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
react-dom.production.min.js:189  Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B_email%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at th (react-dom.production.min.js:152:54)
    at J (react-dom.production.min.js:162:372)
    at Yi (react-dom.production.min.js:192:291)
    at Wk (react-dom.production.min.js:294:1)
    at Vk (react-dom.production.min.js:280:383)
    at Uk (react-dom.production.min.js:280:319)
    at Jk (react-dom.production.min.js:280:180)
    at Ok (react-dom.production.min.js:271:86)
    at Hk (react-dom.production.min.js:268:399)
    at J (scheduler.production.min.js:13:197)
Mi @ react-dom.production.min.js:189
Oi.c.callback @ react-dom.production.min.js:189
ih @ react-dom.production.min.js:144
lk @ react-dom.production.min.js:262
jk @ react-dom.production.min.js:260
ik @ react-dom.production.min.js:259
Xk @ react-dom.production.min.js:283
Qk @ react-dom.production.min.js:281
Hk @ react-dom.production.min.js:269
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
react-dom.production.min.js:189  Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B_phone%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at th (react-dom.production.min.js:152:54)
    at J (react-dom.production.min.js:162:372)
    at Yi (react-dom.production.min.js:192:291)
    at Wk (react-dom.production.min.js:294:1)
    at Vk (react-dom.production.min.js:280:383)
    at Uk (react-dom.production.min.js:280:319)
    at Jk (react-dom.production.min.js:280:180)
    at Ok (react-dom.production.min.js:271:86)
    at Hk (react-dom.production.min.js:268:399)
    at J (scheduler.production.min.js:13:197)
Mi @ react-dom.production.min.js:189
Oi.c.callback @ react-dom.production.min.js:189
ih @ react-dom.production.min.js:144
lk @ react-dom.production.min.js:262
jk @ react-dom.production.min.js:260
ik @ react-dom.production.min.js:259
Xk @ react-dom.production.min.js:283
Qk @ react-dom.production.min.js:281
Hk @ react-dom.production.min.js:269
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
react-dom.production.min.js:152  Uncaught Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B_title%2C%20_name%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at th (react-dom.production.min.js:152:54)
    at J (react-dom.production.min.js:162:372)
    at Yi (react-dom.production.min.js:192:291)
    at Wk (react-dom.production.min.js:294:1)
    at Vk (react-dom.production.min.js:280:383)
    at Uk (react-dom.production.min.js:280:319)
    at Jk (react-dom.production.min.js:280:180)
    at Ok (react-dom.production.min.js:271:86)
    at Hk (react-dom.production.min.js:268:399)
    at J (scheduler.production.min.js:13:197)
th @ react-dom.production.min.js:152
J @ react-dom.production.min.js:162
Yi @ react-dom.production.min.js:192
Wk @ react-dom.production.min.js:294
Vk @ react-dom.production.min.js:280
Uk @ react-dom.production.min.js:280
Jk @ react-dom.production.min.js:280
Ok @ react-dom.production.min.js:271
Hk @ react-dom.production.min.js:268
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
```

**Comment by simlarsen** [comment]
This should now be fixed. Please update to latest
