### ISSUE TITLE
Adding IP or Ping Monitor Fails

### ISSUE THREAD

**Issue by tankerkiller125** [OneUptime/oneuptime#463]
**Describe the bug**
Attempting to add an IP or Ping monitor with an internal IP (172.31.125.4 for example) fails.

Edit: This happens on all IP addresses, both IPv4 and IPv6

**To Reproduce**
1. Create ping monitor
2. Use a local IP address for monitoring
3. Error in console, can not click on next. Additionally, if you attempt to change anything in the criteria section the page will blank out to white.

**Expected behavior**
Should work

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: Latest Stable

**Additional context**
Browser console logs
```
(index):64  cdn.tailwindcss.com should not be used in production. To use Tailwind CSS in production, install it as a PostCSS plugin or use the Tailwind CLI: https://tailwindcss.com/docs/installation
(anonymous) @ (index):64
ma:1  Manifest: Line: 1, column: 1, Syntax error.
react-dom.production.min.js:106  Uncaught Error: Invalid JSON for IP
    at IP.fromJSON (IP.ts:81:19)
    at MonitorStep.fromJSON (MonitorStep.ts:196:34)
    at MonitorStep.clone (MonitorStep.ts:78:28)
    at Object.onChange (MonitorStep.tsx:175:40)
    at onChange (Input.tsx:146:39)
    at Object.Nb (react-dom.production.min.js:54:315)
    at Tb (react-dom.production.min.js:54:468)
    at Ub (react-dom.production.min.js:55:32)
    at nf (react-dom.production.min.js:105:68)
    at se (react-dom.production.min.js:106:380)
fromJSON @ IP.ts:81
fromJSON @ MonitorStep.ts:196
clone @ MonitorStep.ts:78
onChange @ MonitorStep.tsx:175
onChange @ Input.tsx:146
Nb @ react-dom.production.min.js:54
Tb @ react-dom.production.min.js:54
Ub @ react-dom.production.min.js:55
nf @ react-dom.production.min.js:105
se @ react-dom.production.min.js:106
eval @ react-dom.production.min.js:117
Rk @ react-dom.production.min.js:274
Jb @ react-dom.production.min.js:52
hd @ react-dom.production.min.js:109
fd @ react-dom.production.min.js:74
ed @ react-dom.production.min.js:73
react-dom.production.min.js:106  Uncaught Error: Invalid JSON for IP
    at IP.fromJSON (IP.ts:81:19)
    at MonitorStep.fromJSON (MonitorStep.ts:196:34)
    at MonitorStep.clone (MonitorStep.ts:78:28)
    at Object.onChange (MonitorStep.tsx:175:40)
    at onChange (Input.tsx:146:39)
    at Object.Nb (react-dom.production.min.js:54:315)
    at Tb (react-dom.production.min.js:54:468)
    at Ub (react-dom.production.min.js:55:32)
    at nf (react-dom.production.min.js:105:68)
    at se (react-dom.production.min.js:106:380)
fromJSON @ IP.ts:81
fromJSON @ MonitorStep.ts:196
clone @ MonitorStep.ts:78
onChange @ MonitorStep.tsx:175
onChange @ Input.tsx:146
Nb @ react-dom.production.min.js:54
Tb @ react-dom.production.min.js:54
Ub @ react-dom.production.min.js:55
nf @ react-dom.production.min.js:105
se @ react-dom.production.min.js:106
eval @ react-dom.production.min.js:117
Rk @ react-dom.production.min.js:274
Jb @ react-dom.production.min.js:52
hd @ react-dom.production.min.js:109
fd @ react-dom.production.min.js:74
ed @ react-dom.production.min.js:73
react-dom.production.min.js:189  Error: Invalid JSON for IP
    at IP.fromJSON (IP.ts:81:19)
    at MonitorStep.fromJSON (MonitorStep.ts:196:34)
    at MonitorStep.clone (MonitorStep.ts:78:28)
    at Object.onChange (MonitorStep.tsx:314:40)
    at eval (MonitorCriteria.tsx:35:19)
    at Rj (react-dom.production.min.js:244:322)
    at Ik (react-dom.production.min.js:286:88)
    at eval (react-dom.production.min.js:282:391)
    at J (scheduler.production.min.js:13:197)
    at MessagePort.R (scheduler.production.min.js:14:126)
Mi @ react-dom.production.min.js:189
Oi.c.callback @ react-dom.production.min.js:189
ih @ react-dom.production.min.js:144
lk @ react-dom.production.min.js:262
jk @ react-dom.production.min.js:260
ik @ react-dom.production.min.js:259
Xk @ react-dom.production.min.js:283
Qk @ react-dom.production.min.js:281
Fk @ react-dom.production.min.js:273
jg @ react-dom.production.min.js:127
Ik @ react-dom.production.min.js:286
eval @ react-dom.production.min.js:282
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
react-dom.production.min.js:127  Uncaught Error: Invalid JSON for IP
    at IP.fromJSON (IP.ts:81:19)
    at MonitorStep.fromJSON (MonitorStep.ts:196:34)
    at MonitorStep.clone (MonitorStep.ts:78:28)
    at Object.onChange (MonitorStep.tsx:314:40)
    at eval (MonitorCriteria.tsx:35:19)
    at Rj (react-dom.production.min.js:244:322)
    at Ik (react-dom.production.min.js:286:88)
    at eval (react-dom.production.min.js:282:391)
    at J (scheduler.production.min.js:13:197)
    at MessagePort.R (scheduler.production.min.js:14:126)
fromJSON @ IP.ts:81
fromJSON @ MonitorStep.ts:196
clone @ MonitorStep.ts:78
onChange @ MonitorStep.tsx:314
eval @ MonitorCriteria.tsx:35
Rj @ react-dom.production.min.js:244
Ik @ react-dom.production.min.js:286
eval @ react-dom.production.min.js:282
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
```

**Comment by simlarsen** [comment]
This is now fixed!
