### ISSUE TITLE
Preinstall Script Fails

### ISSUE THREAD

**Issue by bionemesis** [OneUptime/oneuptime#472]
The preinstall.sh script failed on the latest up-to-date version of Ubuntu 22.04 and Debian 11.

`/usr/local/lib/node_modules/typescript/lib/typescript.js:139
    for (let i = startIndex ?? 0; i < array.length; i++) {
                             ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at attemptRequireWithV8CompileCache (/usr/local/lib/node_modules/ts-node/dist/util.js:104:16)
    at loadCompiler (/usr/local/lib/node_modules/ts-node/dist/configuration.js:237:56)
    at resolveAndLoadCompiler (/usr/local/lib/node_modules/ts-node/dist/configuration.js:226:16)`

**Comment by bionemesis** [comment]
Ubuntu 20.04, different error but I suspect related to the same underlying issue.

`/usr/local/lib/node_modules/ts-node/dist/child/spawn-child.js:16
        throw new Error('`ts-node-esm` and `ts-node --esm` require node version 12.17.0 or newer.');
        ^

Error: `ts-node-esm` and `ts-node --esm` require node version 12.17.0 or newer.
    at callInChild (/usr/local/lib/node_modules/ts-node/dist/child/spawn-child.js:16:15)
    at bootstrap (/usr/local/lib/node_modules/ts-node/dist/bin.js:43:50)
    at main (/usr/local/lib/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/ts-node/dist/bin-esm.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)`

**Comment by simlarsen** [comment]
Should be fixed now. Please let me know if it still does not work. Please try on a fresh VM.
