### ISSUE TITLE
Bug: Status Page Not Loading / Error: Status Page ID not found

### ISSUE THREAD

**Issue by alexcherka** [OneUptime/oneuptime#853]
**Describe the bug**
Unknow issue as to why Status pages aren't loading properly due to API not being able to find the Status Page Id. 

Also noticed during this loading loop, the other tabs in page aren't bound to the Status Page Id. When clicked during this loop they navigate to a binding property by the looks of it:
`https://<HOST>/status-page/:statusPageId/scheduled-events`
`https://<HOST>/status-page/:statusPageId/incidents`
`https://<HOST>/status-page/:statusPageId/announcements`
`https://<HOST>/status-page/:statusPageId/logout`

**To Reproduce**
1. Go to 'Status Pages' in a Project
2. Click on 'View Status Page' of status page in question.
3. Click on Preview Link
4. Status Page sits in loading loop.

**Expected behavior**
A status page to load.

**Screenshots**
Status Page in a loading loop:
![image](https://github.com/OneUptime/oneuptime/assets/9470827/e67d5198-b87d-4656-aa8f-79ec4b82a644)

Console error for Not Found:
![image](https://github.com/OneUptime/oneuptime/assets/9470827/c8139bd2-d93c-45ce-8385-45e675c25f84)

Url called showing "Error: Status Page ID not found"
![image](https://github.com/OneUptime/oneuptime/assets/9470827/4c456303-b555-4e52-9e08-e8d4b0fc28fb)

Can Confirm status page record does exist in database:
![image](https://github.com/OneUptime/oneuptime/assets/9470827/da90c3a8-4b04-4f4a-a87d-e79ce176a724)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version: Chromium: 114.0.5735.199
 
**Additional context**
Status Page Pod Log:
`{
  _code: 404,
  level: 'error',
  message: 'Not found',
  stack: 'Error: Not found\n' +
    '    at /usr/src/CommonServer/Utils/StartServer.ts:279:13\n' +
    '    at Layer.handle [as handle_request] (/usr/src/CommonServer/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at next (/usr/src/CommonServer/node_modules/express/lib/router/route.js:144:13)\n' +
    '    at Route.dispatch (/usr/src/CommonServer/node_modules/express/lib/router/route.js:114:3)\n' +
    '    at Layer.handle [as handle_request] (/usr/src/CommonServer/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at /usr/src/CommonServer/node_modules/express/lib/router/index.js:284:15\n' +
    '    at param (/usr/src/CommonServer/node_modules/express/lib/router/index.js:365:14)\n' +
    '    at param (/usr/src/CommonServer/node_modules/express/lib/router/index.js:376:14)\n' +
    '    at Function.process_params (/usr/src/CommonServer/node_modules/express/lib/router/index.js:421:3)\n' +
    '    at next (/usr/src/CommonServer/node_modules/express/lib/router/index.js:280:10)\n' +
    '    at Layer.handle [as handle_request] (/usr/src/CommonServer/node_modules/express/lib/router/layer.js:91:12)\n' +
    '    at trim_prefix (/usr/src/CommonServer/node_modules/express/lib/router/index.js:328:13)\n' +
    '    at /usr/src/CommonServer/node_modules/express/lib/router/index.js:286:9\n' +
    '    at Function.process_params (/usr/src/CommonServer/node_modules/express/lib/router/index.js:346:12)\n' +
    '    at next (/usr/src/CommonServer/node_modules/express/lib/router/index.js:280:10)\n' +
    '    at serveStatic (/usr/src/CommonServer/node_modules/serve-static/index.js:75:16)\n' +
    '    at Layer.handle [as handle_request] (/usr/src/CommonServer/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at trim_prefix (/usr/src/CommonServer/node_modules/express/lib/router/index.js:328:13)\n' +
    '    at /usr/src/CommonServer/node_modules/express/lib/router/index.js:286:9\n' +
    '    at Function.process_params (/usr/src/CommonServer/node_modules/express/lib/router/index.js:346:12)\n' +
    '    at next (/usr/src/CommonServer/node_modules/express/lib/router/index.js:280:10)\n' +
    '    at /usr/src/CommonServer/node_modules/express/lib/router/index.js:646:15\n' +
    '    at next (/usr/src/CommonServer/node_modules/express/lib/router/index.js:265:14)\n' +
    '    at Function.handle (/usr/src/CommonServer/node_modules/express/lib/router/index.js:175:3)\n' +
    '    at router (/usr/src/CommonServer/node_modules/express/lib/router/index.js:47:12)\n' +
    '    at Layer.handle [as handle_request] (/usr/src/CommonServer/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at trim_prefix (/usr/src/CommonServer/node_modules/express/lib/router/index.js:328:13)\n' +
    '    at /usr/src/CommonServer/node_modules/express/lib/router/index.js:286:9\n' +
    '    at Function.process_params (/usr/src/CommonServer/node_modules/express/lib/router/index.js:346:12)\n' +
    '    at next (/usr/src/CommonServer/node_modules/express/lib/router/index.js:280:10)\n' +
    '    at /usr/src/CommonServer/node_modules/express/lib/router/index.js:646:15\n' +
    '    at next (/usr/src/CommonServer/node_modules/express/lib/router/index.js:265:14)\n' +
    '    at Function.handle (/usr/src/CommonServer/node_modules/express/lib/router/index.js:175:3)\n' +
    '    at router (/usr/src/CommonServer/node_modules/express/lib/router/index.js:47:12)\n' +
    '    at Layer.handle [as handle_request] (/usr/src/CommonServer/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at trim_prefix (/usr/src/CommonServer/node_modules/express/lib/router/index.js:328:13)\n' +
    '    at /usr/src/CommonServer/node_modules/express/lib/router/index.js:286:9\n' +
    '    at Function.process_params (/usr/src/CommonServer/node_modules/express/lib/router/index.js:346:12)\n' +
    '    at next (/usr/src/CommonServer/node_modules/express/lib/router/index.js:280:10)\n' +
    '    at logRequest (/usr/src/CommonServer/Utils/StartServer.ts:96:5)\n' +
    '    at Layer.handle [as handle_request] (/usr/src/CommonServer/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at trim_prefix (/usr/src/CommonServer/node_modules/express/lib/router/index.js:328:13)\n' +
    '    at /usr/src/CommonServer/node_modules/express/lib/router/index.js:286:9\n' +
    '    at Function.process_params (/usr/src/CommonServer/node_modules/express/lib/router/index.js:346:12)\n' +
    '    at next (/usr/src/CommonServer/node_modules/express/lib/router/index.js:280:10)\n' +
    '    at urlencodedParser (/usr/src/CommonServer/node_modules/body-parser/lib/types/urlencoded.js:82:7)\n' +
    '    at /usr/src/CommonServer/Utils/StartServer.ts:160:9\n' +
    '    at Layer.handle [as handle_request] (/usr/src/CommonServer/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at trim_prefix (/usr/src/CommonServer/node_modules/express/lib/router/index.js:328:13)\n' +
    '    at /usr/src/CommonServer/node_modules/express/lib/router/index.js:286:9\n' +
    '    at Function.process_params (/usr/src/CommonServer/node_modules/express/lib/router/index.js:346:12)\n' +
    '    at next (/usr/src/CommonServer/node_modules/express/lib/router/index.js:280:10)\n' +
    '    at /usr/src/CommonServer/node_modules/body-parser/lib/read.js:137:5\n' +
    '    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)\n' +
    '    at invokeCallback (/usr/src/CommonServer/node_modules/raw-body/index.js:231:16)\n' +
    '    at done (/usr/src/CommonServer/node_modules/raw-body/index.js:220:7)\n' +
    '    at IncomingMessage.onEnd (/usr/src/CommonServer/node_modules/raw-body/index.js:280:7)\n' +
    '    at IncomingMessage.emit (node:events:514:28)\n' +
    '    at IncomingMessage.emit (node:domain:488:12)\n' +
    '    at endReadableNT (node:internal/streams/readable:1408:12)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:82:21)',
  timestamp: '2023-10-18T19:18:44.604Z'
}
{
  message: {
    RequestID: '27b48c30-6deb-11ee-9b1a-f7349805858c',
    PodName: 'NONE',
    HTTPMethod: 'POST',
    Path: '/status-page-api/master-page/b549d5e9-87f5-4901-a5d4-adffa39bfbf7',
    RequestDuration: '13ms',
    ResponseStatus: '404',
    Host: '<HOST>',
    ResponseBody: '{\n  "message": "Not found"\n}'
  },
  level: 'error',
  timestamp: '2023-10-18T19:18:44.608Z'
}
{
  message: {
    RequestID: '53d193d0-6deb-11ee-9b1a-f7349805858c',
    PodName: 'NONE',
    HTTPMethod: 'GET',
    Path: '/status-page-api/master-page/b549d5e9-87f5-4901-a5d4-adffa39bfbf7',
    Host: '<HOST>',
    RequestBody: '{}'
  },
  level: 'info',
  timestamp: '2023-10-18T19:19:58.605Z'
}`

**Comment by alexcherka** [comment]
@simlarsen Updated all containers to 7.0.912 and exact issue still persists.

**Comment by simlarsen** [comment]
@alexcherka are you on one of our enterprise support plans? Happy to hop on a call and debug with you if this is the case. Our test and prod systems are on the same version and we do not have these issues there.

**Comment by simlarsen** [comment]
@alexcherka if you can book a demo call on oneuptime home page, happy to check it out for you.

**Comment by gap579137** [comment]
Just ran into this same issue myself fresh build today

**Comment by max1c** [comment]
Same issue.
